# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 542a24624559e342de4b5b2af60ba7235f616fff9ff0fdb01902ab1d79f6624b7b043655d8c4be2d547d4ad71dfb7fecbf99c8d944b5557f6b3007bba2abfd1c

test:
  secret_key_base: bea55652d4546e5a36d8c9c51d06e6b9a5da5b019030c07aa6c2c5e426155f4c6ac566b4ca20ddeaab9e73463ab01d94807ce8180edc3c9b0cb05c2a37e1675f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
